version: '3.9'
name: 'mediscreen'
services:
  mongo-patients:
    image: mongo:latest
    container_name: 'mediscreen-mongo'
    ports:
      - 27017:27017
  mysql:
    image: mariadb:latest
    container_name: 'mediscreen-maria'
    ports:
      - '3306:3306'
  patient-service:
    image: openjdk:17-jdk-slim
    volumes:
      - '../patient-service/target/patient-service-0.0.1.jar:/home/app.jar'
    command: [ 'java', '-jar', '/home/app.jar' ]
    environment:
      SQL_HOST: mysql
    ports:
      - '8090:8090'
  patient-note-service:
    image: openjdk:17-jdk-slim
    volumes:
      - '../patient-notes-service/target/patient-notes-service-0.0.1.jar:/home/app.jar'
    command: [ 'java', '-jar', '/home/app.jar' ]
    ports:
      - '8070:8070'
  diabetes-detection-service:
    image: openjdk:17-jdk-slim
    volumes:
      - '../diabetes-detection-service/target/diabetes-detection-service-0.0.1.jar:/home/app.jar'
    command: [ 'java', '-jar', '/home/app.jar' ]
    ports:
      - '8050:8050'


